language: python
sudo: false

jobs:
  include:
    - name: "Python 2.7 - Notebook 5 Tests"
      python: "2.7"
      env:
        - TOXENV=py27-notebook5
    - name: "Python 3.5 - Notebook 5 Tests"
      python: "3.5"
      env:
        - TOXENV=py35-notebook5
    - name: "Python 3.6 - Notebook 5 Tests"
      python: "3.6"
      env:
        - TOXENV=py36-notebook5
    - name: "Python 3.5 - Notebook 6 Tests"
      python: "3.5"
      env:
        - TOXENV=py35-notebook6
    - name: "Python 3.6 - Notebook 6 Tests"
      python: "3.6"
      env:
        - TOXENV=py36-notebook6
    - name: "Check [tests] deps not required"
      python: "3.5"
      env:
        - TOXENV=notest
    - name: "Flake8"
      python: "3.5"
      env:
        - TOXENV=flake8

services:
  - postgresql

addons:
  postgresql: "9.5"

install:
  - pip install tox

script:
  - tox

branches:
  only:
    - master
