language: python
sudo: false

matrix:
  include:
    - python: 2.7
      env: NB_VERSION=notebook4
    - python: 2.7
      env: NB_VERSION=notebook5

    - python: 3.4
      env: NB_VERSION=notebook4
    - python: 3.4
      env: NB_VERSION=notebook5

    - python: 3.6
      env: NB_VERSION=notebook4
    - python: 3.6
      env: NB_VERSION=notebook5

    - env: FLAKE8=true
    - env: NOTEST=true

addons:
  postgresql: "9.3"

install:
  - pip install tox

script:
  - if [[ $TRAVIS_PYTHON_VERSION = '2.7' ]]; then tox -e py27-notebook$NB_VERSION; fi
  - if [[ $TRAVIS_PYTHON_VERSION = '3.4' ]]; then tox -e py34-notebook$NB_VERSION; fi
  - if [[ $TRAVIS_PYTHON_VERSION = '3.6' ]]; then tox -e py36-notebook$NB_VERSION; fi
  - if [[ $FLAKE8 = 'true' ]]; then tox -e notest; fi
  - if [[ $NOTEST = 'true' ]]; then tox -e flake8; fi

branches:
  only:
    - master
