language: python
sudo: false
python:
  - "2.7"
  - "3.4"
env:
  - IPYTHON=3
  - IPYTHON=4

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database pgcontents_testing;' -U postgres

script:
  - if [[ $TRAVIS_PYTHON_VERSION = '2.7' ]]; then tox -e py27-ipython-$IPYTHON,flake8; fi
  - if [[ $TRAVIS_PYTHON_VERSION = '3.4' ]]; then tox -e py34-ipython-$IPYTHON,flake8; fi
